// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using seed_a_backend.Api.Data;

#nullable disable

namespace seed_a_backend.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814173357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referenz")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VeranstaltungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Referenz")
                        .IsUnique()
                        .HasDatabaseName("IX_Buchung_Referenz");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Buchungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchungsposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuchungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PreiskategorieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reihe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Spalte")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VeranstaltungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BuchungId");

                    b.HasIndex("PreiskategorieId");

                    b.HasIndex("VeranstaltungId", "Reihe", "Spalte")
                        .IsUnique()
                        .HasDatabaseName("IX_Buchungsposition_AktiverSitzplatz")
                        .HasFilter("[Status] = 0");

                    b.ToTable("Buchungspositionen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Preiskategorie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("VeranstaltungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Preiskategorien");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GangHinweis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GangSpaltenCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReihenCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spalten")
                        .HasColumnType("int");

                    b.Property<string>("SpielstaetteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SpielstaetteId");

                    b.ToTable("Raeume");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Spielstaette", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spielstaetten");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Altersfreigabe")
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DauerMinuten")
                        .HasColumnType("int");

                    b.Property<string>("RaumId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpielstaetteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RaumId");

                    b.HasIndex("SpielstaetteId");

                    b.ToTable("Veranstaltungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchung", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Veranstaltung", "Veranstaltung")
                        .WithMany()
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchungsposition", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Buchung", "Buchung")
                        .WithMany("Positionen")
                        .HasForeignKey("BuchungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("seed_a_backend.Api.Models.Preiskategorie", "Preiskategorie")
                        .WithMany()
                        .HasForeignKey("PreiskategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seed_a_backend.Api.Models.Veranstaltung", "Veranstaltung")
                        .WithMany("Buchungspositionen")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buchung");

                    b.Navigation("Preiskategorie");

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Preiskategorie", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Veranstaltung", "Veranstaltung")
                        .WithMany("Preiskategorien")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Spielstaette", "Spielstaette")
                        .WithMany("Raeume")
                        .HasForeignKey("SpielstaetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spielstaette");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Raum", "Raum")
                        .WithMany("Veranstaltungen")
                        .HasForeignKey("RaumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("seed_a_backend.Api.Models.Spielstaette", "Spielstaette")
                        .WithMany()
                        .HasForeignKey("SpielstaetteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raum");

                    b.Navigation("Spielstaette");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchung", b =>
                {
                    b.Navigation("Positionen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.Navigation("Veranstaltungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Spielstaette", b =>
                {
                    b.Navigation("Raeume");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.Navigation("Buchungspositionen");

                    b.Navigation("Preiskategorien");
                });
#pragma warning restore 612, 618
        }
    }
}
