// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using seed_a_backend.Api.Data;

#nullable disable

namespace seed_a_backend.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815225335_AddBuchungUndBuchungsposition")]
    partial class AddBuchungUndBuchungsposition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gesamtpreis")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referenz")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VeranstaltungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Referenz")
                        .IsUnique();

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Buchungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchungsposition", b =>
                {
                    b.Property<string>("BuchungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SitzplatzCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PreisSnapshot")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("PreiskategorieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BuchungId", "SitzplatzCode");

                    b.HasIndex("PreiskategorieId");

                    b.ToTable("Buchungspositionen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Preiskategorie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("VeranstaltungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Preiskategorien");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GangSpalten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reihen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spalten")
                        .HasColumnType("int");

                    b.Property<string>("SpielstaetteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SpielstaetteId");

                    b.ToTable("Raeume");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Sitzplatzbelegung", b =>
                {
                    b.Property<string>("VeranstaltungId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SitzplatzCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuchungId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VeranstaltungId", "SitzplatzCode");

                    b.HasIndex("BuchungId");

                    b.ToTable("Sitzplatzbelegungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Spielstaette", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spielstaetten");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Altersfreigabe")
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DauerMinuten")
                        .HasColumnType("int");

                    b.Property<string>("RaumId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Zeitpunkt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RaumId");

                    b.ToTable("Veranstaltungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchung", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Veranstaltung", "Veranstaltung")
                        .WithMany()
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchungsposition", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Buchung", "Buchung")
                        .WithMany("Buchungspositionen")
                        .HasForeignKey("BuchungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("seed_a_backend.Api.Models.Preiskategorie", "Preiskategorie")
                        .WithMany()
                        .HasForeignKey("PreiskategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buchung");

                    b.Navigation("Preiskategorie");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Preiskategorie", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Veranstaltung", "Veranstaltung")
                        .WithMany("Preiskategorien")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Spielstaette", "Spielstaette")
                        .WithMany("Raeume")
                        .HasForeignKey("SpielstaetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spielstaette");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Sitzplatzbelegung", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Buchung", null)
                        .WithMany()
                        .HasForeignKey("BuchungId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("seed_a_backend.Api.Models.Veranstaltung", "Veranstaltung")
                        .WithMany()
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Raum", "Raum")
                        .WithMany("Veranstaltungen")
                        .HasForeignKey("RaumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raum");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Buchung", b =>
                {
                    b.Navigation("Buchungspositionen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.Navigation("Veranstaltungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Spielstaette", b =>
                {
                    b.Navigation("Raeume");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.Navigation("Preiskategorien");
                });
#pragma warning restore 612, 618
        }
    }
}
