// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using seed_a_backend.Api.Data;

#nullable disable

namespace seed_a_backend.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815154400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("seed_a_backend.Api.Models.Preiskategorie", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("VeranstaltungId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VeranstaltungId");

                    b.ToTable("Preiskategorien");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GangSpalten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reihen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spalten")
                        .HasColumnType("int");

                    b.Property<string>("SpielstaetteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SpielstaetteId");

                    b.ToTable("Raeume");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Spielstaette", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spielstaetten");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Altersfreigabe")
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DauerMinuten")
                        .HasColumnType("int");

                    b.Property<string>("RaumId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Zeitpunkt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RaumId");

                    b.ToTable("Veranstaltungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Preiskategorie", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Veranstaltung", "Veranstaltung")
                        .WithMany("Preiskategorien")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Spielstaette", "Spielstaette")
                        .WithMany("Raeume")
                        .HasForeignKey("SpielstaetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spielstaette");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.HasOne("seed_a_backend.Api.Models.Raum", "Raum")
                        .WithMany("Veranstaltungen")
                        .HasForeignKey("RaumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raum");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Raum", b =>
                {
                    b.Navigation("Veranstaltungen");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Spielstaette", b =>
                {
                    b.Navigation("Raeume");
                });

            modelBuilder.Entity("seed_a_backend.Api.Models.Veranstaltung", b =>
                {
                    b.Navigation("Preiskategorien");
                });
#pragma warning restore 612, 618
        }
    }
}
